version: "3.9"

services:
  backend:
    container_name: "django_app"
    working_dir: /app/
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DJANGO_EXTERNAL_PORT}:8000"
    volumes:
      - .:/app/
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

volumes:
  postgres_data:
