# Generated by Django 5.2.3 on 2025-06-19 21:23

import comments.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$', 'Разрешены только цифры и буквы латинского алфавита.')], verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('home_page', models.URLField(blank=True, null=True, verbose_name='Home page')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment', verbose_name='Parent Comment')),
            ],
        ),
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=comments.models.user_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'txt'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='comments.comment')),
            ],
        ),
    ]
